News/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.redir_to_feed, name='redir_to_feed'),
    path('admin/', admin.site.urls),
    path('feed/', include('feed.urls')),
    path('account/', include('account.urls')),

    # user login system
    # path('account/login/', 'account.views.login')
]

account/urls.py
from django.urls import path
from django.conf.urls import url


from . import views

app_name = "account"
urlpatterns = [
    path('', views.redir_main, name='redirect_main'),
    path('signup/', views.register, name='signup'),
    path('signup_success/', views.success, name='signup_success'),

    # login
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile')

]

feed/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = "feed"
urlpatterns = [
    path('', views.index, name='index'),
    path('details/news<int:news_id>/', views.details, name='details'),
    path('details/news<int:news_id>/comment',
         views.add_comment, name='add_comment'),
    # url(r'^details/news(?P<news_id>[0-9]+)/', views.details, name='redir'),
    path('random', views.randomArticle, name='randomArticle')

]

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


class UserProfile(models.Model):
    GENDER_CHOICE = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other')
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                related_name='uprofile')
    gender = models.CharField(max_length=6, choices=GENDER_CHOICE,
                              default='Male')
    bio = models.CharField(max_length=300, blank=True, null=True)

    # -------- PREFERENCES -------- #
    email_notif = models.BooleanField(default=True)
    dark_mode = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user)

feed/models.py
from django.db import models
from django.contrib import admin
from django.utils import timezone
from django.contrib.auth.models import User


class NewsAdmin(admin.ModelAdmin):
    list_display = ('__str__', 'pubDate', 'news_date', 'score')
    list_filter = ('pubDate', 'score',)


class News(models.Model):
    class Meta:
        verbose_name_plural = "News"
        ordering = ["-news_date"]

    pubDate = models.DateTimeField(default=timezone.now)
    title = models.CharField('Title', max_length=200)
    data = models.CharField('Data', max_length=400, default='Sample data')
    url = models.CharField('URL', max_length=200)
    news_date = models.CharField('News Date', max_length=10)
    score = models.IntegerField('Point', default=0)
    # post_comments = models.IntegerField('Comments', default=0)

    def __str__(self):
        return str(self.title)


class CommentsAdmin(admin.ModelAdmin):
    list_display = ('news', '__str__', 'user', 'votes')


class Comments(models.Model):
    class Meta:
        verbose_name_plural = "Comments"

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=1000)
    date = models.DateTimeField(default=timezone.now)
    news = models.ForeignKey(News, on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)
    # Score = models.IntegerField(default=0)

    def __str__(self):
        return self.comment

account/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django import forms

from .models import UserProfile


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)
        help_texts = {
            'username': None,
            'password1': None,
            'password2': None,
        }

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.is_staff = True

        if commit:
            user.save()

        return user


class UserProfileForm(ModelForm):
    class Meta():
        model = UserProfile
        exclude = ('user',)


class LoginForm(forms.Form):
    username = username = forms.CharField(label='username', max_length=100)
    password = forms.CharField(widget=forms.PasswordInput())

News/views.py
from django.shortcuts import redirect


def redir_to_feed(request):
    return redirect('feed/')

account/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserForm
from .forms import UserProfileForm
from .forms import LoginForm


def success(request):
    return render(request, 'account/signup_success.html', {})


def redir_main(request):
    return redirect('account:signup')


@login_required
def logout_view(request):
    logout(request)
    return redirect('feed:index')


@login_required
def profile_view(request):
    return render(request, 'account/profile.html')


def login_view(request):
    form = LoginForm(request.POST)
    if request.POST:
        if form.is_valid():
            uname = form.cleaned_data['username']
            pwd = form.cleaned_data['password']
            user = authenticate(request, username=uname, password=pwd)
            if user is not None:
                login(request, user)
                # return render(request, "/feed/index.html", {'user': user})
                return redirect('feed:index')
        else:
            return HttpResponse("Invalid Credentials")
    else:
        form = LoginForm()

    return render(request, 'account/login.html', {'form': form})


def register(request):
    if request.POST:
        uForm = UserForm(request.POST)
        upForm = UserProfileForm(request.POST)
        if uForm.is_valid() and upForm.is_valid():
            user = uForm.save()
            profile = upForm.save(commit=False)
            profile.user = user
            profile.bio = upForm.cleaned_data['bio']
            profile.save()
            messages.success(request, "Account Created")
            return render(request, 'account/signup_success.html', {})

        else:
            messages.error(request, "Error Occured")
            return render(request, 'account/signup.html',
                          {
                              'uForm': UserForm(request.POST),
                              'upForm': UserProfileForm(request.POST)

                          })

    else:
        uForm = UserForm()
        upForm = UserProfileForm()

    return render(request, 'account/signup.html',
                  {
                      'uForm': uForm,
                      'upForm': upForm
                  })

feed/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.shortcuts import redirect, render
from django.contrib import auth
from django.contrib.auth.models import User
from django.template.context_processors import csrf
from .models import News, Comments
from .forms import CommentsForm
from django.contrib.auth.decorators import login_required


def index(request):
    news_list = News.objects.all()[:5]
    return render(request, 'feed/index.html', {'news_list': news_list})


def details(request, news_id):
    news_item = get_object_or_404(News, pk=news_id)
    commentform = CommentsForm()
    context = {}
    context.update(csrf(request))
    user = auth.get_user(request)
    context['news_item'] = news_item
    context['comment'] = News.objects.get(pk=news_id).comments_set.all()

    if user.is_authenticated:
        context['form'] = commentform

    return render(request, 'feed/details.html', context)


def randomArticle(request):
    r_article = News.objects.filter(
        pubDate__lte=timezone.now()).order_by('?')[:1][0]
    return render(request, 'feed/random.html', {'news_item': r_article})


@login_required
def add_comment(request, news_id):
    news_item = get_object_or_404(News, pk=news_id)
    form = CommentsForm(request.POST)
    if request.POST:
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = auth.get_user(request)
            comment.news = News.objects.get(pk=news_id)
            comment.comment = form.cleaned_data['comment']
            comment.save()
        return redirect('feed:details', news_id=news_item.pk)
    else:
        form = CommentsForm()
    return render(request, 'feed/comment.html', {'form': form, 'news_item': news_item})

feed/templates/feed/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons|La+Belle+Aurore" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/materialize.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>

    <title>Le Journal</title>
</head>
<style>
    .nav-wrapper,
    .page-footer {
        /*background: linear-gradient(127deg, rgba(82, 219, 190, 0.918),
        rgb(47, 158, 192), rgba(222, 109, 245, 0.863))*/
        background: linear-gradient(to left, #3e5151, #decba4);
        /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
    }

    body {
        background-color: #eceff1;
    }
</style>

<body>
    <!-- START OF HEADER  -->
    <div class="navbar-fixed zz">
        <nav>
            <div class="nav-wrapper green lighten-1">

                <div class="container">
                    <a href="{% url 'feed:index' %}" class="brand-logo left hide-on-med-and-down" style="font-family:La Belle Aurore,Verdana">
                        Le Journal
                    </a>
                    <a href="{% url 'feed:index' %}" class="brand-logo center hide-on-large-only" style="font-family:La Belle Aurore,Verdana">
                        Le Journal
                    </a>
                    <a href="#" data-activates="mobile-menu" class="hide-on-large-only sidemenu">
                        <i class="material-icons">menu</i>
                    </a>
                    <ul id="nav-mobile" class="right hide-on-med-and-down">
                        <li>
                            <a href="{% url 'feed:randomArticle' %}">Random News</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'account:profile' %}">{{user.username}}</a>
                        </li>
                        <li>
                            <a href="{% url 'account:logout' %}">Logout</a>
                        </li>

                        {% else %}
                        <li>
                            <a href="{% url 'account:login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'account:signup' %}">Register</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>

            </div>
        </nav>
    </div>
    <ul class="sidenav" id="mobile-menu">
        <li>
            <div class="user-view">
                <div class="background" style="background: linear-gradient(170deg, #3e5151, #88acac);">

                </div>
                <a href="#user">
                    <img class="circle" src="{% static 'assets/images/prof.png' %}">
                </a>
                {% if user.is_authenticated %}
                <a href="#name">
                    <span class="white-text name">Hello, {{ user.username }}</span>
                </a>
                {% else %}
                <a href="#name">
                    <span class="white-text name">Hello, User</span>
                </a>
                {% endif %}
                <a href="#name">
                    <span class=" white-text name ">&nbsp;</span>
                </a>

            </div>
        </li>
        <li style="margin-top:7em ">
            <a href="{% url 'feed:randomArticle' %} ">Random News</a>
        </li>
        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'account:profile' %} ">{{user.username}}</a>
        </li>
        <li>
            <a href="{% url 'account:logout' %} ">Logout</a>
        </li>

        {% else %}
        <li>
            <a href="{% url 'account:login' %} ">Login</a>
        </li>
        <li>
            <a href="{% url 'account:signup' %} ">Register</a>
        </li>
        {% endif %}
    </ul>
    </ul>
    <!-- END OF HEADER  -->


    <!-- START OF CONTENT  -->
    {% block content %} {% endblock %}
    <!-- END OF CONTENT  -->

    <div class="fixed-action-btn " onclick="funcExpand() ">
        <a class="btn-floating btn-large red ">
            <i class="large material-icons ">fullscreen</i>
        </a>
    </div>

    <!-- START OF FOOTER  -->
    <footer class="page-footer green lighten-1 ">
        <div class="container ">
            <div class="row ">
                <div class="col l12 m12 s12 center ">
                    <h4 style="font-family:La Belle Aurore ">Le Journal</h4>
                    <p>A minimal news app, made with
                        <i class="tiny red-text material-icons ">favorite</i>
                    </p>
                </div>
            </div>
        </div>
        <div class="footer-copyright small ">
            <div class="container center ">
                © 2018 Copyright
                <a class="red-text text-accent-3 " href="https://www.github.com/snbk97 "> &nbsp; Sayan Bhowmik
                </a>
                <a class="grey-text text-lighten-4 right " href="#! "></a>
            </div>
        </div>
    </footer>
    <!-- END OF FOOTER  -->


</body>
<script type="text/javascript ">
    $(document).ready(function () {
        $(".sidemenu ").sideNav();
        $('.dropdown-trigger').dropdown();

    });

</script>

</html>

feed/templates/feed/index.html
{% extends "feed/base.html" %} {% block javascript %}
<script type="text/javascript">
    $(document).ready(function () {
        Materialize.toast('I am a toast!', 4000)
    });
</script> {% endblock javascript %} {% block content %}
<!--Content-->
<script type="text/javascript">
    var count = 1
    function funcExpand() {
        count++
        if (count % 2 == 0) {
            document.getElementById("index-container").className = "container"
        } else {
            document.getElementById("index-container").className += "xyz"
        }
        if (count <= 2) {
            Materialize.toast('This button is for adjusting content fit', 3000)
        }

    }
</script>

<div class="had-container" id="index-container">
    <style>
        #new-row:last-child {
            margin-bottom: 10%
        }
    </style>
    <div>
        <ul>
            {% for news in news_list %}
            <li id="item{{ forloop.counter }}">
                <a href="{% url 'feed:details' news.id %}"></a>
                <div class="row" id="news-row">
                    <div class="col l10 m12 s12 push-l1">
                        <div class="card hoverable " onclick="location.href= '{% url 'feed:details' news.id %}' ">
                            <div class="card-content grey-text text-darken-3 ">
                                <span class="card-title ">
                                    <a href="{% url 'feed:details' news.id %} ">{{ news.title }}</a>
                                </span>
                                <p class="">I am a very simple card. I am good at containing small bits of information. I am convenient
                                    because I require little markup to use effectively.</p>
                            </div>
                            <div class="card-action " style="border:none ">
                                <a class="teal-text text-lighten-2" href="# ">{{news.score}} point{{news.score|pluralize}}</a>
                                <a class="teal-text text-lighten-2" href="# ">{{ news.comments_set.count }} comment{{news.post_comments|pluralize}}</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
        </ul>
    </div>
</div>
<!--Content-->
{% endblock content %}